defmodule Ichor.InstructionOverlay do
  @moduledoc """
  Generates instruction overlay files (CLAUDE.md) for spawned agents.

  Each agent gets a tailored CLAUDE.md with:
    - Role definition and capability constraints
    - Task assignment with acceptance criteria
    - File scope restrictions
    - Quality gates (compile, test, etc.)
    - Communication protocol (inbox check, completion report)

  Inspired by Overstory's overlay.ts template system.
  """

  @doc """
  Generate a CLAUDE.md overlay string for an agent.

  Options:
    - `:name` - Agent name
    - `:capability` - Role: "builder", "scout", "reviewer", "lead"
    - `:task` - Task map with "subject", "description", "acceptance_criteria", "done_when"
    - `:file_scope` - List of file paths this agent should focus on
    - `:quality_gates` - List of commands to pass before reporting completion
    - `:team_name` - Team this agent belongs to
    - `:extra_instructions` - Additional instructions appended to the overlay
  """
  @spec generate(map()) :: String.t()
  def generate(opts) do
    name = opts[:name] || "agent"
    capability = opts[:capability] || "builder"
    gates = opts[:quality_gates] || default_gates()

    [
      header(name, capability),
      role_section(capability),
      task_section(opts[:task]),
      file_scope_section(opts[:file_scope] || []),
      quality_gates_section(gates),
      communication_section(name, opts[:team_name]),
      completion_section(capability, gates),
      extra_section(opts[:extra_instructions])
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join("\n")
  end

  defp header(name, capability) do
    """
    # Agent: #{name}
    > Role: #{capability} | Generated by Ichor at #{DateTime.utc_now() |> DateTime.to_iso8601()}

    You are an autonomous agent managed by Ichor. Follow the instructions below precisely.
    """
  end

  defp role_section("builder") do
    """
    ## Role: Builder

    You are a builder agent. Your job is to implement the assigned task by writing code.
    - Read existing code before modifying it
    - Follow project conventions and patterns
    - Keep changes minimal and focused on the task
    - Run quality gates before reporting completion
    """
  end

  defp role_section("scout") do
    """
    ## Role: Scout

    You are a scout agent. Your job is to explore and gather information.
    - Read files, search code, and analyze architecture
    - Do NOT modify any files
    - Report findings via send_message MCP tool
    - Use Read, Glob, Grep, and Bash (read-only) tools only
    """
  end

  defp role_section("reviewer") do
    """
    ## Role: Reviewer

    You are a reviewer agent. Your job is to review code changes.
    - Check for bugs, security issues, and code quality problems
    - Verify changes match the task requirements
    - Report findings via send_message MCP tool
    - Do NOT modify code unless explicitly asked to fix issues
    """
  end

  defp role_section("lead") do
    """
    ## Role: Lead

    You are a lead agent coordinating a team of workers.
    - Break tasks into subtasks and assign to workers
    - Monitor progress via check_inbox MCP tool
    - Verify completed work meets quality gates
    - Report team status to the operator
    """
  end

  defp role_section(_) do
    """
    ## Role: Worker

    You are a worker agent. Complete the assigned task following project conventions.
    """
  end

  defp task_section(nil), do: nil

  defp task_section(task) when is_map(task) do
    subject = task["subject"] || task[:subject] || "Untitled"
    description = task["description"] || task[:description] || ""
    criteria = task["acceptance_criteria"] || task[:acceptance_criteria] || []
    done_when = task["done_when"] || task[:done_when]

    """
    ## Task Assignment

    **#{subject}**

    #{description}

    ### Acceptance Criteria

    #{format_criteria(criteria)}
    #{format_done_when(done_when)}
    """
  end

  defp format_criteria([]), do: "- [ ] Implementation matches task description"

  defp format_criteria(criteria) do
    Enum.map_join(criteria, "\n", &"- [ ] #{&1}")
  end

  defp format_done_when(nil), do: ""
  defp format_done_when(cmd), do: "\n**Verification command:** `#{cmd}`\n"

  defp extra_section(nil), do: nil
  defp extra_section(text), do: "\n## Additional Instructions\n\n#{text}\n"

  defp file_scope_section([]), do: nil

  defp file_scope_section(files) do
    file_list = Enum.map_join(files, "\n", &"- `#{&1}`")

    """
    ## File Scope

    Focus your work on these files. Do not modify files outside this scope without explicit approval.

    #{file_list}
    """
  end

  defp quality_gates_section(gates) do
    gate_text =
      Enum.map_join(Enum.with_index(gates, 1), "\n", fn {gate, i} -> "#{i}. `#{gate}`" end)

    """
    ## Quality Gates

    Before reporting task completion, ALL of these must pass:

    #{gate_text}

    Do not report completion until every gate passes cleanly.
    """
  end

  defp communication_section(name, team_name) do
    """
    ## Communication Protocol
    #{team_text(team_name)}
    Your agent name is **#{name}**. Use the MCP tools to communicate:

    - `check_inbox` -- Check for new messages every few turns
    - `send_message` -- Report progress, ask questions, or signal completion
    - `acknowledge_message` -- Mark messages as read after processing

    Ichor is running at `http://localhost:#{ichor_port()}`.
    """
  end

  defp team_text(nil), do: ""
  defp team_text(name), do: "\nYou are a member of team **#{name}**."

  defp completion_section(capability, _quality_gates) when capability in ["scout", "reviewer"] do
    """
    ## Completion Protocol

    When your analysis is complete:
    1. Send your findings via `send_message` to the operator or lead
    2. Include a structured summary of what you found
    3. Signal completion: `send_message(to: "operator", content: "DONE: <summary>")`
    """
  end

  defp completion_section(_capability, quality_gates) do
    gate_text = gates_as_steps(quality_gates)

    """
    ## Completion Protocol

    When your implementation is complete:
    #{gate_text}
    #{length(quality_gates) + 1}. Send completion report: `send_message(to: "operator", content: "DONE: <summary of changes>")`

    If any quality gate fails, fix the issue and re-run ALL gates before reporting.
    """
  end

  defp gates_as_steps(gates) do
    Enum.map_join(Enum.with_index(gates, 1), "\n", fn {gate, i} ->
      "#{i}. Run `#{gate}` -- must pass cleanly"
    end)
  end

  defp default_gates do
    ["mix compile --warnings-as-errors", "mix test"]
  end

  # ── File Writing ───────────────────────────────────────────────────

  @doc """
  Write the overlay and hooks files to the agent's working directory.

  Creates:
    - `.claude/ICHOR_OVERLAY.md` -- instruction overlay
    - `.claude/settings.local.json` -- hooks pointing back to Ichor
  """
  @spec write_session_files(String.t(), map()) :: :ok
  def write_session_files(cwd, opts) do
    overlay_content = generate(opts)
    overlay_path = Path.join(cwd, ".claude/ICHOR_OVERLAY.md")

    File.mkdir_p!(Path.dirname(overlay_path))
    File.write!(overlay_path, overlay_content)
    :ok
  end

  defp ichor_port do
    Application.get_env(:ichor, IchorWeb.Endpoint, [])
    |> get_in([:http, :port]) || 4005
  end
end
