defmodule Ichor.Repo.Migrations.ReshapeFactoryProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :roadmap_items, {:array, :map}, default: []
      add :artifacts, {:array, :map}, default: []
      add :build_log, :text
      add :path, :text
      add :picked_up_at, :utc_datetime_usec
      add :picked_up_by, :text
      add :run_id, :text
      add :team_name, :text
      add :status, :text, null: false
      add :signals_subscribed, {:array, :text}, default: []
      add :signals_emitted, {:array, :text}, default: []
      add :dependencies, {:array, :text}, default: []
      add :architecture, :text
      add :use_cases, {:array, :text}, default: []
      add :features, {:array, :text}, default: []
      add :version, :text
      add :topic, :text
      add :signal_interface, :text
      add :subsystem, :text
      add :planning_stage, :text, null: false
      add :constraints, {:array, :text}, default: []
      add :stakeholders, {:array, :text}, default: []
      add :description, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    execute("""
    INSERT INTO projects (
      id,
      title,
      description,
      stakeholders,
      constraints,
      planning_stage,
      subsystem,
      signal_interface,
      topic,
      version,
      features,
      use_cases,
      architecture,
      dependencies,
      signals_emitted,
      signals_subscribed,
      status,
      team_name,
      run_id,
      picked_up_by,
      picked_up_at,
      path,
      build_log,
      artifacts,
      roadmap_items,
      inserted_at,
      updated_at
    )
    SELECT
      gn.id,
      COALESCE(gn.title, mp.title),
      COALESCE(gn.description, mp.description, ''),
      COALESCE(gn.stakeholders, '[]'),
      COALESCE(gn.constraints, '[]'),
      COALESCE(gn.status, 'discover'),
      mp.subsystem,
      mp.signal_interface,
      mp.topic,
      COALESCE(mp.version, '0.1.0'),
      COALESCE(mp.features, '[]'),
      COALESCE(mp.use_cases, '[]'),
      mp.architecture,
      COALESCE(mp.dependencies, '[]'),
      COALESCE(mp.signals_emitted, '[]'),
      COALESCE(mp.signals_subscribed, '[]'),
      COALESCE(mp.status, 'proposed'),
      mp.team_name,
      mp.run_id,
      mp.picked_up_by,
      mp.picked_up_at,
      mp.path,
      mp.build_log,
      COALESCE((
        SELECT json_group_array(
          json_object(
            'id', ga.id,
            'kind', ga.kind,
            'title', ga.title,
            'content', ga.content,
            'code', ga.code,
            'status', ga.status,
            'mode', ga.mode,
            'summary', ga.summary,
            'adr_codes', COALESCE(ga.adr_codes, '[]'),
            'feature_code', ga.feature_code,
            'participants', COALESCE(ga.participants, '[]')
          )
        )
        FROM genesis_artifacts ga
        WHERE ga.node_id = gn.id
      ), json('[]')),
      COALESCE((
        SELECT json_group_array(
          json_object(
            'id', gri.id,
            'kind', gri.kind,
            'number', gri.number,
            'title', gri.title,
            'status', gri.status,
            'governed_by', COALESCE(gri.governed_by, '[]'),
            'goals', COALESCE(gri.goals, '[]'),
            'goal', gri.goal,
            'parent_uc', gri.parent_uc,
            'allowed_files', COALESCE(gri.allowed_files, '[]'),
            'blocked_by', COALESCE(gri.blocked_by, '[]'),
            'steps', COALESCE(gri.steps, '[]'),
            'done_when', gri.done_when,
            'owner', gri.owner,
            'parent_id', gri.parent_id
          )
        )
        FROM genesis_roadmap_items gri
        WHERE gri.node_id = gn.id
      ), json('[]')),
      gn.inserted_at,
      gn.updated_at
    FROM genesis_nodes gn
    LEFT JOIN mes_projects mp ON mp.id = gn.mes_project_id
    """)

    execute("""
    INSERT INTO projects (
      id,
      title,
      description,
      stakeholders,
      constraints,
      planning_stage,
      subsystem,
      signal_interface,
      topic,
      version,
      features,
      use_cases,
      architecture,
      dependencies,
      signals_emitted,
      signals_subscribed,
      status,
      team_name,
      run_id,
      picked_up_by,
      picked_up_at,
      path,
      build_log,
      artifacts,
      roadmap_items,
      inserted_at,
      updated_at
    )
    SELECT
      mp.id,
      mp.title,
      mp.description,
      json('[]'),
      json('[]'),
      'discover',
      mp.subsystem,
      mp.signal_interface,
      mp.topic,
      COALESCE(mp.version, '0.1.0'),
      COALESCE(mp.features, '[]'),
      COALESCE(mp.use_cases, '[]'),
      mp.architecture,
      COALESCE(mp.dependencies, '[]'),
      COALESCE(mp.signals_emitted, '[]'),
      COALESCE(mp.signals_subscribed, '[]'),
      COALESCE(mp.status, 'proposed'),
      mp.team_name,
      mp.run_id,
      mp.picked_up_by,
      mp.picked_up_at,
      mp.path,
      mp.build_log,
      json_array(
        json_object(
          'id', mp.id,
          'kind', 'brief',
          'title', mp.title,
          'content', mp.description,
          'adr_codes', json('[]'),
          'participants', json('[]')
        )
      ),
      json('[]'),
      mp.inserted_at,
      mp.updated_at
    FROM mes_projects mp
    WHERE NOT EXISTS (
      SELECT 1
      FROM genesis_nodes gn
      WHERE gn.mes_project_id = mp.id
    )
    """)
  end

  def down do
    drop table(:projects)
  end
end
