defmodule Observatory.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :ended_at, :utc_datetime
      add :started_at, :utc_datetime
      add :status, :text
      add :model, :text
      add :agent_type, :text
      add :source_app, :text, null: false
      add :session_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:sessions, [:session_id, :source_app],
             name: "sessions_unique_session_index"
           )

    create table(:events, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tool_name, :text
      add :model_name, :text
      add :summary, :text
      add :payload, :map, null: false, default: %{}
      add :hook_event_type, :text, null: false
      add :session_id, :text, null: false
      add :source_app, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:events, [:id], name: "events_unique_event_index")
  end

  def down do
    drop_if_exists unique_index(:events, [:id], name: "events_unique_event_index")

    drop table(:events)

    drop_if_exists unique_index(:sessions, [:session_id, :source_app],
                     name: "sessions_unique_session_index"
                   )

    drop table(:sessions)
  end
end