defmodule Ichor.Repo.Migrations.RenameProjectSubsystemToPlugin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :subsystem

      add :plugin, :text
    end

    execute("""
    UPDATE projects
    SET plugin = subsystem
    WHERE plugin IS NULL
    """)
  end

  def down do
    alter table(:projects) do
      remove :plugin
      # This is the `down` migration of the statement:
      #
      #     remove :subsystem
      #

      # add :subsystem, :text
    end
  end
end
