defmodule Ichor.Repo.Migrations.RemoveTaskCountFromPipelines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pipelines) do
      remove :task_count
    end
  end

  def down do
    alter table(:pipelines) do
      add :task_count, :bigint
    end
  end
end
