defmodule Ichor.Repo.Migrations.RenamePipelineNodeIdToProjectId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:dag_runs), :node_id, to: :project_id
  end

  def down do
    rename table(:dag_runs), :project_id, to: :node_id
  end
end
