defmodule Observatory.Repo.Migrations.Sprint5Domains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:token_usages, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tool_name, :text
      add :estimated_cost_cents, :bigint, null: false
      add :cache_write_tokens, :bigint, null: false
      add :cache_read_tokens, :bigint, null: false
      add :output_tokens, :bigint, null: false
      add :input_tokens, :bigint, null: false
      add :model_name, :text, null: false
      add :source_app, :text, null: false
      add :session_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:token_usages, [:id], name: "token_usages_unique_token_usage_index")

    create table(:tasks, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :blocked_by, {:array, :text}, null: false, default: []
      add :blocks, {:array, :text}, null: false, default: []
      add :active_form, :text
      add :team_name, :text
      add :owner, :text
      add :status, :text, null: false
      add :description, :text
      add :subject, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:tasks, [:id], name: "tasks_unique_task_index")

    create table(:notes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :text, :text, null: false
      add :event_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:notes, [:id], name: "notes_unique_note_index")

    create table(:messages, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :team_name, :text
      add :read, :boolean, null: false
      add :message_type, :text, null: false
      add :content, :text, null: false
      add :to_session_id, :text
      add :from_session_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:messages, [:id], name: "messages_unique_message_index")
  end

  def down do
    drop_if_exists unique_index(:messages, [:id], name: "messages_unique_message_index")

    drop table(:messages)

    drop_if_exists unique_index(:notes, [:id], name: "notes_unique_note_index")

    drop table(:notes)

    drop_if_exists unique_index(:tasks, [:id], name: "tasks_unique_task_index")

    drop table(:tasks)

    drop_if_exists unique_index(:token_usages, [:id],
                     name: "token_usages_unique_token_usage_index"
                   )

    drop table(:token_usages)
  end
end