defmodule Ichor.Repo.Migrations.RenamePipelineStorage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:dag_runs), to: table(:pipelines)
    rename table(:pipelines), :job_count, to: :task_count

    rename table(:dag_jobs), to: table(:pipeline_tasks)

    drop_if_exists index(:pipeline_tasks, [:run_id, :external_id],
                     name: "dag_jobs_run_external_index"
                   )

    create unique_index(:pipeline_tasks, [:run_id, :external_id],
             name: "pipeline_tasks_run_external_index"
           )
  end

  def down do
    drop_if_exists index(:pipeline_tasks, [:run_id, :external_id],
                     name: "pipeline_tasks_run_external_index"
                   )

    create unique_index(:pipeline_tasks, [:run_id, :external_id],
             name: "dag_jobs_run_external_index"
           )

    rename table(:pipeline_tasks), to: table(:dag_jobs)

    rename table(:pipelines), :task_count, to: :job_count
    rename table(:pipelines), to: table(:dag_runs)
  end
end
