defmodule Ichor.Repo.Migrations.AddRepoFieldsToSettingsProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings_projects) do
      add :repo_name, :text
      add :repo_url, :text
    end
  end

  def down do
    alter table(:settings_projects) do
      remove :repo_url
      remove :repo_name
    end
  end
end