defmodule Observatory.Repo.Migrations.CreateWorkshopBlueprints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workshop_team_blueprints, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :cwd, :text
      add :default_model, :text, null: false
      add :strategy, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:workshop_team_blueprints, [:name],
             name: "workshop_team_blueprints_unique_name_index"
           )

    create table(:workshop_spawn_links, primary_key: false) do
      add :team_blueprint_id,
          references(:workshop_team_blueprints,
            column: :id,
            name: "workshop_spawn_links_team_blueprint_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :to_slot, :bigint, null: false
      add :from_slot, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:workshop_comm_rules, primary_key: false) do
      add :team_blueprint_id,
          references(:workshop_team_blueprints,
            column: :id,
            name: "workshop_comm_rules_team_blueprint_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :via_slot, :bigint
      add :policy, :text, null: false
      add :to_slot, :bigint, null: false
      add :from_slot, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:workshop_agent_blueprints, primary_key: false) do
      add :team_blueprint_id,
          references(:workshop_team_blueprints,
            column: :id,
            name: "workshop_agent_blueprints_team_blueprint_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :canvas_y, :bigint, null: false
      add :canvas_x, :bigint, null: false
      add :quality_gates, :text
      add :file_scope, :text
      add :persona, :text
      add :permission, :text, null: false
      add :model, :text, null: false
      add :capability, :text, null: false
      add :name, :text, null: false
      add :slot, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:events) do
      add :tmux_session, :text
    end
  end

  def down do
    alter table(:events) do
      remove :tmux_session
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workshop_agent_blueprints` table without the `workshop_agent_blueprints_team_blueprint_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workshop_agent_blueprints)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workshop_comm_rules` table without the `workshop_comm_rules_team_blueprint_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workshop_comm_rules)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workshop_spawn_links` table without the `workshop_spawn_links_team_blueprint_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workshop_spawn_links)

    drop_if_exists unique_index(:workshop_team_blueprints, [:name],
                     name: "workshop_team_blueprints_unique_name_index"
                   )

    drop table(:workshop_team_blueprints)
  end
end