defmodule Ichor.Repo.Migrations.AddTeamMembersAndToolScopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  and then extended with a data backfill for existing workshop teams.
  """

  use Ecto.Migration

  def up do
    created_team_members? = not table_exists?("workshop_team_members")

    if created_team_members? do
      create table(:workshop_team_members, primary_key: false) do
        add :agent_type_id,
            references(:workshop_agent_types,
              column: :id,
              name: "workshop_team_members_agent_type_id_fkey",
              type: :uuid
            )

        add :team_id,
            references(:workshop_blueprints,
              column: :id,
              name: "workshop_team_members_team_id_fkey",
              type: :uuid
            ),
            null: false

        add :updated_at, :utc_datetime_usec, null: false
        add :inserted_at, :utc_datetime_usec, null: false
        add :canvas_y, :bigint, null: false
        add :canvas_x, :bigint, null: false
        add :tool_scope, {:array, :text}, null: false, default: []
        add :quality_gates, :text, null: false
        add :file_scope, :text, null: false
        add :extra_instructions, :text, null: false
        add :permission, :text, null: false
        add :model, :text, null: false
        add :capability, :text, null: false
        add :name, :text, null: false
        add :position, :bigint, null: false
        add :slot, :bigint, null: false
        add :id, :uuid, null: false, primary_key: true
      end
    end

    if not index_exists?("workshop_team_members_team_slot_index") do
      create unique_index(:workshop_team_members, [:team_id, :slot],
               name: "workshop_team_members_team_slot_index"
             )
    end

    if not column_exists?("workshop_agent_types", "default_tools") do
      alter table(:workshop_agent_types) do
        add :default_tools, {:array, :text}, default: []
      end
    end

    flush()

    if created_team_members? or team_members_empty?() do
      migrate_blueprint_agents_into_team_members()
    end
  end

  def down do
    alter table(:workshop_agent_types) do
      remove :default_tools
    end

    drop_if_exists unique_index(:workshop_team_members, [:team_id, :slot],
                     name: "workshop_team_members_team_slot_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workshop_team_members` table without the `workshop_team_members_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workshop_team_members` table without the `workshop_team_members_agent_type_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workshop_team_members)
  end

  defp migrate_blueprint_agents_into_team_members do
    rows =
      repo().query!(
        "SELECT id, agents, inserted_at, updated_at FROM workshop_blueprints ORDER BY inserted_at ASC"
      ).rows

    for [team_id, agents, inserted_at, updated_at] <- rows do
      agents
      |> decode_agents()
      |> Enum.with_index()
      |> Enum.each(fn {agent, index} ->
        repo().query!(
          """
          INSERT INTO workshop_team_members
            (id, team_id, agent_type_id, slot, position, name, capability, model, permission,
             extra_instructions, file_scope, quality_gates, tool_scope, canvas_x, canvas_y,
             inserted_at, updated_at)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
          """,
          [
            Ecto.UUID.generate(),
            team_id,
            Map.get(agent, "agent_type_id"),
            Map.get(agent, "slot") || index + 1,
            index,
            Map.get(agent, "name") || "agent-#{index + 1}",
            Map.get(agent, "capability") || "builder",
            Map.get(agent, "model") || "sonnet",
            Map.get(agent, "permission") || "default",
            Map.get(agent, "persona") || "",
            Map.get(agent, "file_scope") || "",
            Map.get(agent, "quality_gates") || "",
            Map.get(agent, "tools") || [],
            Map.get(agent, "canvas_x") || 40,
            Map.get(agent, "canvas_y") || 30,
            inserted_at,
            updated_at
          ]
        )
      end)
    end
  end

  defp decode_agents(agents) when is_binary(agents) do
    case Jason.decode(agents) do
      {:ok, decoded} when is_list(decoded) -> decoded
      _ -> []
    end
  end

  defp decode_agents(agents) when is_list(agents), do: agents
  defp decode_agents(_), do: []

  defp table_exists?(table_name) do
    repo().query!(
      "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ? LIMIT 1",
      [table_name]
    ).rows != []
  end

  defp index_exists?(index_name) do
    repo().query!(
      "SELECT name FROM sqlite_master WHERE type = 'index' AND name = ? LIMIT 1",
      [index_name]
    ).rows != []
  end

  defp column_exists?(table_name, column_name) do
    repo().query!("PRAGMA table_info(#{table_name})").rows
    |> Enum.any?(fn [_cid, name | _rest] -> name == column_name end)
  end

  defp team_members_empty? do
    repo().query!("SELECT COUNT(*) FROM workshop_team_members").rows == [[0]]
  end
end
