defmodule Observatory.Repo.Migrations.AddWorkshopAgentTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workshop_agent_types, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sort_order, :bigint
      add :color, :text
      add :default_quality_gates, :text
      add :default_file_scope, :text
      add :default_persona, :text
      add :default_permission, :text, null: false
      add :default_model, :text, null: false
      add :capability, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:workshop_agent_types, [:name],
             name: "workshop_agent_types_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workshop_agent_types, [:name],
                     name: "workshop_agent_types_unique_name_index"
                   )

    drop table(:workshop_agent_types)
  end
end