defmodule Ichor.Repo.Migrations.RenameWorkshopBlueprintsToTeams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    if table_exists?("workshop_blueprints") and not table_exists?("workshop_teams") do
      rename table(:workshop_blueprints), to: table(:workshop_teams)
    end

    drop_if_exists unique_index(:workshop_teams, [:name],
                     name: "workshop_blueprints_unique_name_index"
                   )

    create_if_not_exists unique_index(:workshop_teams, [:name],
                           name: "workshop_teams_unique_name_index"
                         )
  end

  def down do
    drop_if_exists unique_index(:workshop_teams, [:name],
                     name: "workshop_teams_unique_name_index"
                   )

    if table_exists?("workshop_teams") and not table_exists?("workshop_blueprints") do
      rename table(:workshop_teams), to: table(:workshop_blueprints)
    end

    create_if_not_exists unique_index(:workshop_blueprints, [:name],
                           name: "workshop_blueprints_unique_name_index"
                         )
  end

  defp table_exists?(name) do
    %{rows: rows} =
      repo().query!("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?", [name])

    rows != []
  end
end
