defmodule Observatory.Repo.Migrations.AddEventDetails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :tool_use_id, :text
      add :cwd, :text
      add :permission_mode, :text
      add :duration_ms, :bigint
    end
  end

  def down do
    alter table(:events) do
      remove :duration_ms
      remove :permission_mode
      remove :cwd
      remove :tool_use_id
    end
  end
end
