defmodule Ichor.Repo.Migrations.AddStoredEventsAndCheckpoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stored_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :topic, :text, null: false
      add :key, :text
      add :occurred_at, :utc_datetime_usec, null: false
      add :causation_id, :text
      add :correlation_id, :text
      add :data, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:signal_checkpoints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :signal_module, :text, null: false
      add :key, :text, null: false
      add :last_event_id, :text
      add :last_event_occurred_at, :utc_datetime_usec, null: false
      add :event_count, :bigint, null: false, default: 0
      add :last_signal_emitted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:signal_checkpoints, [:signal_module, :key],
             name: "signal_checkpoints_module_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:signal_checkpoints, [:signal_module, :key],
                     name: "signal_checkpoints_module_key_index"
                   )

    drop table(:signal_checkpoints)

    drop table(:stored_events)
  end
end
