defmodule Ichor.Repo.Migrations.AddProjectOutputKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :output_kind, :text, null: false, default: "plugin"
    end
  end

  def down do
    alter table(:projects) do
      remove :output_kind
    end
  end
end
