defmodule Ichor.Repo.Migrations.AddWorkshopAgentsAndPrompts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:workshop_teams) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :agents
    # end
    # 
    create table(:workshop_prompts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :content, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:workshop_prompts, [:name], name: "workshop_prompts_unique_name_index")

    create table(:workshop_agents, primary_key: false) do
      add :team_id,
          references(:workshop_teams,
            column: :id,
            name: "workshop_agents_team_id_fkey",
            type: :uuid
          )

      add :agent_type_id,
          references(:workshop_agent_types,
            column: :id,
            name: "workshop_agents_agent_type_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :canvas_y, :bigint, null: false
      add :canvas_x, :bigint, null: false
      add :position, :bigint, null: false
      add :tool_scope, {:array, :text}, null: false, default: []
      add :quality_gates, :text, null: false
      add :file_scope, :text, null: false
      add :permission, :text, null: false
      add :model, :text, null: false
      add :instructions, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workshop_agents` table without the `workshop_agents_agent_type_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workshop_agents` table without the `workshop_agents_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workshop_agents)

    drop_if_exists unique_index(:workshop_prompts, [:name],
                     name: "workshop_prompts_unique_name_index"
                   )

    drop table(:workshop_prompts)

    # alter table(:workshop_teams) do
    # This is the `down` migration of the statement:
    #
    #     remove :agents
    #
    # 
    # add :agents, {:array, :map}, default: []
    # end
    # 
  end
end