defmodule Ichor.Repo.Migrations.InitialPostgresSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workshop_teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :strategy, :text, null: false, default: "one_for_one"
      add :default_model, :text, null: false, default: "sonnet"
      add :cwd, :text, default: ""
      add :agents, {:array, :map}, default: []
      add :spawn_links, {:array, :map}, default: []
      add :comm_rules, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workshop_teams, [:name], name: "workshop_teams_unique_name_index")

    create table(:workshop_team_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slot, :bigint, null: false
      add :position, :bigint, null: false, default: 0
      add :name, :text, null: false
      add :capability, :text, null: false, default: "builder"
      add :model, :text, null: false, default: "sonnet"
      add :permission, :text, null: false, default: "default"
      add :extra_instructions, :text, null: false, default: ""
      add :file_scope, :text, null: false, default: ""
      add :quality_gates, :text, null: false, default: ""
      add :tool_scope, {:array, :text}, null: false, default: []
      add :canvas_x, :bigint, null: false, default: 40
      add :canvas_y, :bigint, null: false, default: 30

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_id,
          references(:workshop_teams,
            column: :id,
            name: "workshop_team_members_team_id_fkey",
            type: :uuid
          ), null: false

      add :agent_type_id, :uuid
    end

    create table(:workshop_prompts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :content, :text, null: false, default: ""
      add :category, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workshop_prompts, [:name], name: "workshop_prompts_unique_name_index")

    create table(:workshop_agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :role, :text
      add :model, :text, null: false, default: "sonnet"
      add :cwd, :text, null: false, default: ""
      add :instructions, :text, null: false, default: ""
      add :permission, :text, null: false, default: "default"
      add :file_scope, :text, null: false, default: ""
      add :quality_gates, :text, null: false, default: ""
      add :tool_scope, {:array, :text}, null: false, default: []
      add :position, :bigint, null: false, default: 0
      add :canvas_x, :bigint, null: false, default: 40
      add :canvas_y, :bigint, null: false, default: 30

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_type_id, :uuid, null: false
      add :team_id, :uuid
    end

    create table(:workshop_agent_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workshop_team_members) do
      modify :agent_type_id,
             references(:workshop_agent_types,
               column: :id,
               name: "workshop_team_members_agent_type_id_fkey",
               type: :uuid
             )
    end

    create unique_index(:workshop_team_members, [:team_id, :slot],
             name: "workshop_team_members_team_slot_index"
           )

    alter table(:workshop_agents) do
      modify :agent_type_id,
             references(:workshop_agent_types,
               column: :id,
               name: "workshop_agents_agent_type_id_fkey",
               type: :uuid
             )

      modify :team_id,
             references(:workshop_teams,
               column: :id,
               name: "workshop_agents_team_id_fkey",
               type: :uuid
             )
    end

    alter table(:workshop_agent_types) do
      add :name, :text, null: false
      add :description, :text
      add :capability, :text, null: false, default: "builder"
      add :default_model, :text, null: false, default: "sonnet"
      add :default_provider, :text, default: "claude"
      add :default_permission, :text, null: false, default: "default"
      add :default_persona, :text, null: false, default: ""
      add :default_file_scope, :text, null: false, default: ""
      add :default_quality_gates, :text, null: false, default: "mix compile --warnings-as-errors"
      add :default_tools, {:array, :text}, null: false, default: []
      add :system_prompt, :text
      add :color, :text, null: false, default: ""
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workshop_agent_types, [:name],
             name: "workshop_agent_types_unique_name_index"
           )

    create table(:webhook_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :target_url, :text, null: false
      add :payload, :text, null: false
      add :signature, :text
      add :status, :text, default: "pending"
      add :attempt_count, :bigint, default: 0
      add :next_retry_at, :utc_datetime
      add :agent_id, :text, null: false
      add :webhook_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:settings_projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :is_active, :boolean, default: true
      add :location, :map, null: false
      add :repo_name, :text
      add :repo_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text, null: false
      add :stakeholders, {:array, :text}, default: []
      add :constraints, {:array, :text}, default: []
      add :planning_stage, :text, null: false, default: "discover"
      add :output_kind, :text, null: false, default: "plugin"
      add :plugin, :text
      add :signal_interface, :text
      add :topic, :text
      add :version, :text, default: "0.1.0"
      add :features, {:array, :text}, default: []
      add :use_cases, {:array, :text}, default: []
      add :architecture, :text
      add :dependencies, {:array, :text}, default: []
      add :signals_emitted, {:array, :text}, default: []
      add :signals_subscribed, {:array, :text}, default: []
      add :status, :text, null: false, default: "proposed"
      add :team_name, :text
      add :run_id, :text
      add :picked_up_by, :text
      add :picked_up_at, :utc_datetime_usec
      add :path, :text
      add :build_log, :text
      add :artifacts, {:array, :map}, default: []
      add :roadmap_items, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:pipelines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text, null: false
      add :source, :text, null: false
      add :project_id, :text
      add :project_path, :text
      add :tmux_session, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:pipeline_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :external_id, :text, null: false
      add :subtask_id, :text
      add :subject, :text, null: false
      add :description, :text
      add :goal, :text
      add :allowed_files, {:array, :text}, default: []
      add :steps, {:array, :text}, default: []
      add :done_when, :text
      add :blocked_by, {:array, :text}, default: []
      add :status, :text, null: false, default: "pending"
      add :owner, :text
      add :priority, :text, null: false, default: "medium"
      add :wave, :bigint
      add :acceptance_criteria, {:array, :text}, default: []
      add :phase_label, :text
      add :tags, {:array, :text}, default: []
      add :notes, :text
      add :claimed_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :run_id,
          references(:pipelines, column: :id, name: "pipeline_tasks_run_id_fkey", type: :uuid),
          null: false
    end

    create unique_index(:pipeline_tasks, [:run_id, :external_id],
             name: "pipeline_tasks_run_external_index"
           )

    create table(:hitl_intervention_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :agent_id, :text
      add :operator_id, :text, null: false
      add :action, :text, null: false
      add :details, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cron_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :agent_id, :text, null: false
      add :payload, :text, null: false
      add :next_fire_at, :utc_datetime, null: false
      add :is_one_time, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:cron_jobs)

    drop table(:hitl_intervention_events)

    drop_if_exists unique_index(:pipeline_tasks, [:run_id, :external_id],
                     name: "pipeline_tasks_run_external_index"
                   )

    drop constraint(:pipeline_tasks, "pipeline_tasks_run_id_fkey")

    drop table(:pipeline_tasks)

    drop table(:pipelines)

    drop table(:projects)

    drop table(:settings_projects)

    drop table(:webhook_deliveries)

    drop_if_exists unique_index(:workshop_agent_types, [:name],
                     name: "workshop_agent_types_unique_name_index"
                   )

    alter table(:workshop_agent_types) do
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :color
      remove :system_prompt
      remove :default_tools
      remove :default_quality_gates
      remove :default_file_scope
      remove :default_persona
      remove :default_permission
      remove :default_provider
      remove :default_model
      remove :capability
      remove :description
      remove :name
    end

    drop constraint(:workshop_agents, "workshop_agents_agent_type_id_fkey")

    drop constraint(:workshop_agents, "workshop_agents_team_id_fkey")

    alter table(:workshop_agents) do
      modify :team_id, :uuid
      modify :agent_type_id, :uuid
    end

    drop_if_exists unique_index(:workshop_team_members, [:team_id, :slot],
                     name: "workshop_team_members_team_slot_index"
                   )

    drop constraint(:workshop_team_members, "workshop_team_members_agent_type_id_fkey")

    alter table(:workshop_team_members) do
      modify :agent_type_id, :uuid
    end

    drop table(:workshop_agent_types)

    drop table(:workshop_agents)

    drop_if_exists unique_index(:workshop_prompts, [:name],
                     name: "workshop_prompts_unique_name_index"
                   )

    drop table(:workshop_prompts)

    drop constraint(:workshop_team_members, "workshop_team_members_team_id_fkey")

    drop table(:workshop_team_members)

    drop_if_exists unique_index(:workshop_teams, [:name],
                     name: "workshop_teams_unique_name_index"
                   )

    drop table(:workshop_teams)
  end
end
